import type {GetServerSideProps, NextPage, NextPageContext} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export type HomeType = NextPage & {
  data: string,
}

function Home(props: HomeType) {
  const { data } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div id="sphere-content" style={{width: '100vw'}} dangerouslySetInnerHTML={{__html: data}}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const headers = new Headers();
  headers.append("Access-Control-Allow-Origin", "*");
  headers.append('Access-Control-Allow-Headers', "*");
  const res = await fetch(`${process.env.NEXT_CONTENT_RENDERER_BASE_URL}/content/e648d2f6-fe1e-4052-8a51-4f7da09874e6`)
  const data = await res.text()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}

export default Home
